linters:
  enable-all: true
  disable:
    - forbidigo # enable later
    - gci # import order is handled by gofumpt, gci conflicts with it
    # deprecated linters
    - structcheck
    - ifshort
    - exhaustruct
    - exhaustivestruct
    - scopelint
    - nosnakecase
    - golint
    - maligned
    - varcheck
    - interfacer
    - deadcode


linters-settings:
  lll:
    # Max line length, lines longer will be reported.
    # '\t' is counted as 1 character by default, and can be changed with the 
    # tab-width option.
    line-length: 80

issues:
  exclude-rules:
    - path: '_test\.go'
      linters:
        - funlen # allow long functions in test files
        - lll # allow more than 80 characters in test files
    - path: 'const\.go'
      linters:
        - lll # allow more than 80 characters in const files